export const GET_ALL_USERS_LOAD = "GET_ALL_USERS_LOAD";
export const GET_ALL_USERS_FAIL = "GET_ALL_USERS_FAIL";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
